$ANSIBLE_VAULT;1.1;AES256
36623762656533306534376265636365376264323766346133373139366138333866663965653764
6463376463353930366432333563646130346463386139330a336335356166323738373836303230
63653937383266303036653634383938636630656237383337366264343532666333353264353437
3434393466623961620a363966653532386561363232663833346237623565373564353030313132
37636436323863313566623035653037633738366632353031643962613561656432343930333064
6338363337613735623562323835393339396433376535666238
